{
	"version": 1619641841,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/imagens-sheet0.png",
		"images/imagens-sheet1.png",
		"images/imagens-sheet2.png",
		"images/imagens-sheet3.png",
		"images/imagens-sheet4.png",
		"images/canvas.png",
		"images/borda-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/personagem1-sheet0.png",
		"images/personagem1-sheet1.png",
		"images/personagem1-sheet2.png",
		"images/personagem2-sheet0.png",
		"images/personagem2-sheet1.png",
		"images/personagem2-sheet2.png",
		"images/bloco1-sheet0.png",
		"images/linha-sheet0.png",
		"images/linha2-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite11-sheet1.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite15-sheet1.png",
		"images/sprite17-sheet0.png",
		"images/btnjogar_2-sheet0.png",
		"images/btn_selecao-sheet0.png",
		"images/btn_destaque-sheet0.png",
		"images/empate1-sheet0.png",
		"images/bt_som-sheet0.png",
		"images/bt_som-sheet1.png",
		"images/joia-sheet0.png",
		"images/btn_creditos-sheet0.png",
		"images/logolied-sheet0.png",
		"images/btncredits-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/btn_creditos2-sheet0.png",
		"images/sprite3-sheet0.png",
		"media/aplausos.m4a",
		"media/aplausos.ogg",
		"media/florest_music.ogg",
		"media/empate.ogg",
		"media/whatsapp audio 2021-04-14 at 14.48.06 (1).ogg",
		"media/whatsapp ptt 2021-04-16 at 17.15.46.ogg",
		"media/whatsapp audio 2021-04-19 at 12.41.19.ogg",
		"media/whatsapp audio 2021-04-19 at 12.41.20.ogg",
		"media/whatsapp audio 2021-04-15 at 13.45.47 (online-audio-converter.com).ogg",
		"media/click.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}